### PR TITLE
Only add deprectation handler if sapi is CLI

### PR DESCRIPTION
**Pull request by dantleech**
- Prevent deprecation handler adding warnings to web requests in tests
- Also add `CMF_DISABLE_DEPRECATION_HANDLER` environment variable

### CODE REVIEW

**Comment by WouterJ** [comment]
:+1:

**Comment by WouterJ** [comment]
Do we have a bundle/component testing for 2.7 already, so we can test this right after the merge?

**Comment by WouterJ** [comment]
Hmm, we should improve this a bit, because it should still catch deprecations during the creation of the JSON response. Otherwise, we miss important information about usage of deprecated things.

So, we should still catch them during the request, save them somewhere and show then in the error output.

**Comment by dantleech** [comment]
I think this is OK as it is. The deprecation warnings show on the CLI tests, which is where we want them. The CLI tests should cover everything that any HTTP tests cover.

**Comment by WouterJ** [comment]
> The CLI tests should cover everything that any HTTP tests cover.

That's currently not the case (for instance, ResourceRestBundle). This means we have no insight in any incompatibility issues for ResourceRestBundle. And there are more bundles like that.

**Comment by dantleech** [comment]
Guess this is now a non issue

**Pull request closed without merging**
