### PR TITLE
Allow symfony 6

### PR DESCRIPTION
**Pull request by acrobat**
| Q             | A
| ------------- | ---
| Branch?       | "master" for new features / the branch of the current release for fixes
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | yes and no 😄 (see comment below)
| Deprecations? | no
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

I'm not sure if I can make the return typehints like this or if it's a bc-break. This is a testing package and the class should be used as is?

Otherwise I can update the PR to do a class check and only change the return types when using symfony 6

### CODE REVIEW

**Comment by dbu** [comment]
if anything overwrites the bootKernel method again, this BC break would bite them. but as this is an internal tool, i just checked core and routing, and they don't do that. so i think this is good enough. thanks!

**Comment by dbu** [comment]
https://github.com/symfony-cmf/Testing/releases/tag/4.1.0

**Comment by acrobat** [comment]
Thanks @dbu for the quick release, I can continue to make cmf routing and routing-bundle sf6 compatible 😄

**Comment by dbu** [comment]
thank YOU for the good work!

**Pull request merged**
