### PR TITLE
[Do not merge] Test php ^5.6 || ^7.0 support

### PR DESCRIPTION
**Pull request by covex-nn**
| Q             | A
| ------------- | ---
| Branch?       | "master" for new features / the branch of the current release for fixes
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | yes/no
| Deprecations? | yes/no
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any
| License       | MIT
| Doc PR        | reference to the documentation PR, if any

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
Hi @covex-nn thanks for the commits, but we do have a dev-kit in cmf world also, wo i will try to trigger your change from there and we will see if it works. 
In general i am not sure if should continue suporting php < 7.0 as sonata it self droped everything < 7.1
@dbu wdyt?

**Comment by covex-nn** [comment]
Hi =)
The main goal of this PR was to find out if `symfony-cmf/testing` still works with php5.6 and php7.0, and it works :tada: So, may be it is too early to switch to php ^7.1? Otherwise `SonataDoctrinePhpcrAdminBundle` cannot be tested, released and updated in the future - it is not stable. See last travis builds for [2.x](https://travis-ci.org/sonata-project/SonataDoctrinePhpcrAdminBundle/builds/395047521) and [master](https://travis-ci.org/sonata-project/SonataDoctrinePhpcrAdminBundle/builds/393887099)

This PR should be closed, i guess. I reached all goals )

**Comment by covex-nn** [comment]
@dbu is it possible to get support for php>=5.6 back for 2.1 release?

**Comment by covex-nn** [comment]
Closing this PR in favour of https://github.com/symfony-cmf/dev-kit/pull/4

**Pull request closed without merging**
