### PR TITLE
Pattern has been renamed to Path in Sf 2.2

### PR DESCRIPTION
**Pull request by WouterJ**
Let's try to remove some deprecation notices

### CODE REVIEW

**Comment by dantleech** [comment]
I guess no BC problems with this change? Looks like we need to update the DatabaseListenerTestCase too, but thats not related to this.

**Comment by WouterJ** [comment]
As we only promise support for Sf >= 2.3, this is not a BC break. My goal is to fix those too and then see what's lefleft.

**Comment by lsmith77** [comment]
needs a minor update in the tests due to a change in master:
```
1) Symfony\Cmf\Component\Testing\Tests\Phpunit\DatabaseTestListenerTest::testPhpcrTestSuite
Expectation failed for method name is equal to <string:setArguments> when invoked at sequence index 0
Parameter 0 for invocation Symfony\Component\Process\ProcessBuilder::setArguments(Array (...)) does not match expected value.
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => 'doctrine:phpcr:init:dbal'
     1 => '--drop'
+    2 => '--force'
 )
```

**Comment by lsmith77** [comment]
ok fixed .. I also removed the calls to ``$kernel->init()``

**Comment by lsmith77** [comment]
can one of you two review this?

**Pull request merged**
