### PR TITLE
Copied deprecation error handler from core

### PR DESCRIPTION
**Pull request by WouterJ**
This was done in Symfony to replace the long deprecated errors in the Travis tests with a short summary at the end of the tests.

@nicolas-grekas are you ok with this? I'm happy to remove it if you don't agree (we'll remove it anyway if you create a component)

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
No pb for me. Just be sure to follow our patches on this class.
You should add the typical Symfony copyright header imho

**Comment by lsmith77** [comment]
+1

**Comment by WouterJ** [comment]
I've added the CMF license header with a slight change to include the Symfony package and Fabien's copyright. I think this is ready to be merged now

**Comment by dantleech** [comment]
This is adding deprecation warnings to the JSON response in a behat test...

**Pull request merged**
