### PR TITLE
no longer enable csrf protection

### PR DESCRIPTION
**Pull request by lsmith77**

### CODE REVIEW

**Comment by dantleech** [comment]
Looks like we are getting a new failure with PHP 5.3:

````
Fatal error: Cannot access self:: when no class scope is active in /home/travis/build/symfony-cmf/Testing/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php on line 150
```

Though not related to this PR.

What is the reason for not "disabling" the CSRF option out of interest?

**Comment by lsmith77** [comment]
indeed I doubt that we have any tests that require CSRF protection .. but I do not know for sure.

**Comment by lsmith77** [comment]
we also have an issue with PHP7:
```
PHP Fatal error:  Class Symfony\Cmf\Component\Testing\Phpunit\DatabaseTestListener contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (PHPUnit_Framework_TestListener::addWarning) in /home/travis/build/symfony-cmf/Testing/src/Phpunit/DatabaseTestListener.php on line 21
```

**Comment by lsmith77** [comment]
reported the PHP 5.3 issue:
https://github.com/symfony/phpunit-bridge/commit/d6ddb75f1ee66be87d363d96193c85fc5a734a72#commitcomment-14807973

**Comment by lsmith77** [comment]
@dantleech looks good now ..

**Comment by dbu** [comment]
looks good to me. should we merge? do we then also tag a new version?

**Comment by WouterJ** [comment]
@dbu before tagging 1.3.0, we should merge https://github.com/symfony-cmf/Testing/pull/116 imo

**Pull request merged**
