### PR TITLE
Symfony 6 config compatibility

### PR DESCRIPTION
**Pull request by acrobat**
| Q             | A
| ------------- | ---
| Branch?       | "master" for new features / the branch of the current release for fixes
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

Follow up of #210. This PR adds compatibility with symfony 6 config changes (removed/renamed options)

### CODE REVIEW

**Review by dbu — APPROVED** [review]
oh, so i was a bit trigger-happy tagging the release?

i will merge this and then wait for you to confirm if we should tag another release.

changes look clean, agree to go with php files to have the flexibility.

**Comment by acrobat** [comment]
Great I will let you know! These changes were needed to make the tests compatible with symfony 6 in symfony-cmf/routing-bundle

**Comment by alexander-schranz** [comment]
anything blocking here to create a tag?

https://github.com/symfony-cmf/Testing/compare/4.1.0...master

**Comment by dbu** [comment]
i tagged https://github.com/symfony-cmf/Testing/releases/tag/4.4.1

**Pull request merged**
