### PR TITLE
increase phpcr-odm version

### PR DESCRIPTION
**Pull request by ElectricMaxxx**
to update relating bundles.

### CODE REVIEW

**Comment by wouterj** [comment]
I have no idea what you're trying to do here. This package supports Symfony 2.8 and this package supports PHPCR ODM 1.x, I have no idea why we should drop it. (in fact, it means we can no longer test against Symfony 2.8 in the CMF bundles)

**Comment by ElectricMaxxx** [comment]
what i really whanted to do is that ...

just updating to phpcr-odm 2.0 as that will hopefully save lots of dependency problems when trying to update sonata-admin-integration's phpcr-odm to 2.0.

**Comment by wouterj** [comment]
Either you or I are completely confused.

All CMF bundles do already support PHPCR ODM 2.0. The Sonata integration bundle does too.
Besides that, this package also already allows PHPCR ODM 2.0.

I see (a) not what this PR is trying to do (otherwise than dropping PHPCR ODM 1.x support, which I'm against) and (b) do not understand the "dependency problems" you're talking about the past days.

**Comment by ElectricMaxxx** [comment]
When confusion is in the room it is mostly me :-( Sorry

I tried to do a `composer require doctrine/phpcr-odm:^2.0` in `sonata-admin-integration` and got dependency issues with this bundle here. But mostly that is my fault too.

**Pull request closed without merging**
