### PR TITLE
Update doctrine dependencies to a safe version for PHP 7.0

### PR DESCRIPTION
**Pull request by jordisala1991**
| Q             | A
| ------------- | ---
| Branch?       | 2.0
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

This with a release will help us fixing SonataDoctrinePHPCRAdminBundle master branch

### CODE REVIEW

**Comment by dbu** [comment]
i think this is a good illustration of https://github.com/symfony-cmf/testing/pull/163#issuecomment-354408369 - the conflict is more with the bundles using the testing component, not with the testing component itself.

**Comment by jordisala1991** [comment]
Yes indeed.

Basicaly this problem is for bundles that define their php restriction like this: >=5.3.
This means that 7.0 will pass when maybe it is not even compatible with that version. I just upgraded to a version where it says ^5.x || ^7.0

**Comment by dbu** [comment]
i tagged 2.0.2 with this.

**Comment by jordisala1991** [comment]
Let's try on the sonata bundle

**Pull request merged**
