### PR TITLE
Add Symfony4 compatibility

### PR DESCRIPTION
**Pull request by jordisala1991**
| Q             | A
| ------------- | ---
| Branch?       | 2.0
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

If we want to add SF4 to SonataDoctrinePHPCRAdminBundle at some point we will need this also.
There was a PR directly on master not so long ago, not sure why it wasn't on 2.0.

### CODE REVIEW

**Comment by dbu** [comment]
i think the PR to master is https://github.com/symfony-cmf/testing/pull/167 

is this PR you propose here backporting things from master? i wonder if we should not just have things move to testing 2.1 when they want symfony 4?

**Comment by jordisala1991** [comment]
Well, that could be an option :P

**Comment by jordisala1991** [comment]
Closing at is it probably too much for a thing already implemented on master

**Comment by dbu** [comment]
okay, lets bump requirements to testing 2.1 in places where we want symfony 4. (its not released though, and probably needs more work)

**Pull request closed without merging**
